"""
Quick Test - Post to Facebook
Simple test to post to Facebook
"""

import sys
import io
from datetime import datetime
from pathlib import Path

# Fix encoding for Windows console
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

sys.path.insert(0, str(Path(__file__).parent / "integrations"))

from facebook_integration import post_to_facebook

def quick_facebook_test():
    """Quick test for Facebook posting"""

    content = f"""AI Employee Test - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

This post was automatically generated by AGents!

#AI #Automation #FTE2026"""

    print("=" * 60)
    print("QUICK FACEBOOK TEST")
    print("=" * 60)
    print(f"\nContent:\n{content}\n")
    print("Starting Facebook post...")

    success = post_to_facebook(content, headless=False)

    if success:
        print("\n✅ Facebook post published successfully!")
    else:
        print("\n❌ Failed to publish Facebook post")

    return success

if __name__ == "__main__":
    quick_facebook_test()
