"""
Quick Test - Post to Facebook
Test Facebook posting (should work immediately)
"""

import sys
import io
from datetime import datetime
from pathlib import Path

# Fix encoding for Windows console
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

sys.path.insert(0, str(Path(__file__).parent / "integrations"))

from facebook_integration import post_to_facebook

def quick_facebook_test():
    """Quick test for Facebook posting"""

    content = f"""🤖 AGents AI Employee Test

This post was automatically generated by my AI Employee system!

Posted at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

#AI #Automation #AGents #FTE2026"""

    print("=" * 60)
    print("QUICK FACEBOOK TEST")
    print("=" * 60)
    print(f"\nContent:\n{content}\n")
    print("Starting Facebook post...")
    print("\n⏳ Opening browser and logging in...")
    print("   (This may take 30-60 seconds)\n")

    success = post_to_facebook(content, headless=False)

    if success:
        print("\n✅ Facebook post published successfully!")
        print("   Check your Facebook profile to see the post!")
    else:
        print("\n❌ Failed to publish Facebook post")
        print("   Check the browser window for any errors")

    return success

if __name__ == "__main__":
    quick_facebook_test()
